name: Node CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install, build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        run: |
          make setup
          make build
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
